### ISSUE TITLE
EL6 I/O error with fuse-overlayfs 0.4.1

### ISSUE THREAD

**Issue by carlwgeorge** [containers/fuse-overlayfs#86]
On Fedora 30, when using `fuse-overlayfs-0.4.1-0.dev.git1ff7c64.fc30.x86_64` from updates-testing, installing packages in a CentOS 6 container results in an I/O error.

```
$ podman run -it --rm centos:6
[root@15e67895f0ba /]# yum --disablerepo \* install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Examining /var/tmp/yum-root-zLjjSS/epel-release-latest-6.noarch.rpm: epel-release-6-8.noarch
Marking /var/tmp/yum-root-zLjjSS/epel-release-latest-6.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:6-8 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================
 Package                        Arch                     Version                Repository                                       Size
======================================================================================================================================
Installing:
 epel-release                   noarch                   6-8                    /epel-release-latest-6.noarch                    22 k

Transaction Summary
======================================================================================================================================
Install       1 Package(s)

Total size: 22 k
Installed size: 22 k
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : epel-release-6-8.noarch                                                                                            1/1
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/yum/rpmtrans.py", line 444, in callback
    self._instCloseFile(  bytes, total, h )
  File "/usr/lib/python2.6/site-packages/yum/rpmtrans.py", line 526, in _instCloseFile
    self.base.history.trans_data_pid_end(pid, state)
  File "/usr/lib/python2.6/site-packages/yum/history.py", line 868, in trans_data_pid_end
    """, ('TRUE', self._tid, pid, state))
  File "/usr/lib/python2.6/site-packages/yum/sqlutils.py", line 168, in executeSQLQmark
    return cursor.execute(query, params)
sqlite3.OperationalError: disk I/O error
error: python callback <bound method RPMTransaction.callback of <yum.rpmtrans.RPMTransaction instance at 0x1875ab8>> failed, aborting!
[root@15e67895f0ba /]# echo $?      
1
[root@15e67895f0ba /]# rpm -q epel-release
epel-release-6-8.noarch
```

The rpm is installed afterwards, but yum exits with a status of 1.  `registry.access.redhat.com/rhel6` has the same issue.  This is as a non-root user.  The problem is *not* reproducible as root.  It appears to be limited to EL6, because I cannot reproduce it with CentOS 7 or RHEL 7 containers.  Downgrading to `fuse-overlayfs-0.3-10.dev.gita7c8295.fc30.x86_64` fixes the problem.

Other installed packages:
- `podman-1.4.0-2.fc30.x86_64`
- `container-selinux-2.106-1.gitfc7111d.fc30.noarch`
- `containers-common-0.1.37-0.gite079f9d.fc30.x86_64`
- `containernetworking-plugins-0.7.5-1.fc30.x86_64`

**Comment by giuseppe** [comment]
do you have any chance to try out https://github.com/containers/fuse-overlayfs/pull/87 ?

**Comment by carlwgeorge** [comment]
[fuse-overlayfs-0.4.2-0.dev.git7bc2dd9.fc30](https://bodhi.fedoraproject.org/updates/FEDORA-2019-1fba8e63f5) does indeed solve the problem.  Thanks for the quick resolution!
